package se325.lab03.parolee.dto;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import se325.lab03.parolee.domain.Address;
import se325.lab03.parolee.domain.Curfew;
import se325.lab03.parolee.domain.Gender;
import se325.lab03.parolee.domain.Movement;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import se325.lab03.parolee.jackson.LocalDateDeserializer;
import se325.lab03.parolee.jackson.LocalDateSerializer;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Class to represent a Parolee.
 * <p>
 * An instance of this class represents a DTO Parolee. A DTO Parolee includes
 * a subset of Parolee data, and DTO Parolees objects are exchanged between
 * clients and the Parolee Web service.
 * <p>
 * A DTO Parolee is described by:
 * - Personal details: lastname, firstname, gender, date-of-birth, home address;
 * - Curfew: any constraints on the Parolee's location;
 * - Criminal profile: criminal history of the Parolee;
 * - Last know location: timestamped latitude/longitude position.
 * <p>
 * A Parolee is uniquely identified by an id value of type long.
 */
public class Parolee {

    private long id;

    private String lastName;

    private String firstName;

    private Gender gender;

    private LocalDate dateOfBirth;

    private Address homeAddress;

    private Curfew curfew;

    private Movement lastKnownPosition;

    public Parolee() {
    }

    /**
     * Constructs a DTO Parolee instance. This method is intended to be called
     * by Web service clients when creating new Parolees. The id field is not
     * required because it is generated by the Web service. Similarly, the
     * last-known-position field is not required. Of the constructor's
     * parameters, all fields must be non-null with the exception of curfew,
     * which is optional (not all Parolees are subject to a curfew).
     */
    public Parolee(String lastname,
                   String firstname,
                   Gender gender,
                   LocalDate dateOfBirth,
                   Address homeAddress,
                   Curfew curfew) throws IllegalArgumentException {
        this(0, lastname, firstname, gender, dateOfBirth, homeAddress, curfew, null);
    }

    /**
     * Constructs a DTO Parolee instance. This method should NOT be called by
     * Web Service clients. It is intended to be used by the Web Service
     * implementation when creating a DTO Parolee from a domain-model Parolee
     * object.
     */
    public Parolee(long id,
                   String lastname,
                   String firstname,
                   Gender gender,
                   LocalDate dateOfBirth,
                   Address homeAddress,
                   Curfew curfew,
                   Movement lastKnownPosition) {
        this.id = id;
        lastName = lastname;
        firstName = firstname;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.homeAddress = homeAddress;
        this.curfew = curfew;
        this.lastKnownPosition = lastKnownPosition;
    }

    public long getId() {
        return id;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastname) {
        lastName = lastname;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstname) {
        firstName = firstname;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonDeserialize(using = LocalDateDeserializer.class)
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Address getHomeAddress() {
        return homeAddress;
    }

    public void setHomeAddress(Address homeAddress) {
        this.homeAddress = homeAddress;
    }

    public Curfew getCurfew() {
        return curfew;
    }

    public void setCurfew(Curfew curfew) {
        this.curfew = curfew;
    }

    public Movement getLastKnownPosition() {
        return lastKnownPosition;
    }

    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        DateTimeFormatter dOfBFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");

        buffer.append("Parolee: { [");
        buffer.append(id);
        buffer.append("]; ");
        if (lastName != null) {
            buffer.append(lastName);
            buffer.append(", ");
        }
        if (firstName != null) {
            buffer.append(firstName);
        }
        buffer.append("; ");
        if (gender != null) {
            buffer.append(gender);
        }
        buffer.append("; ");

        if (dateOfBirth != null) {
            buffer.append(dOfBFormatter.format(dateOfBirth));
        }
        buffer.append("\n  ");
        if (homeAddress != null) {
            buffer.append(homeAddress);
        }

        buffer.append("\n  ");
        if (curfew != null) {
            buffer.append("\n  Curfew from ");
            buffer.append(timeFormatter.format(curfew.getStartTime()));
            buffer.append(" to ");
            buffer.append(timeFormatter.format(curfew.getEndTime()));
            buffer.append(" @ ");

            if (homeAddress != null && homeAddress.equals(curfew.getConfinementAddress())) {
                buffer.append("home");
            } else {
                buffer.append(curfew.getConfinementAddress());
            }
        } else {
            buffer.append("No curfew conditions");
        }

        buffer.append(" }");

        return buffer.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof Parolee))
            return false;
        if (obj == this)
            return true;

        Parolee rhs = (Parolee) obj;
        return new EqualsBuilder().
                append(id, rhs.id).
                append(lastName, rhs.lastName).
                append(firstName, rhs.firstName).
                append(gender, rhs.gender).
                append(dateOfBirth, rhs.dateOfBirth).
                append(homeAddress, rhs.homeAddress).
                isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 31).
                append(id).
                append(lastName).
                append(firstName).
                append(gender).
                append(dateOfBirth).
                append(homeAddress).
                toHashCode();
    }
}


